Read local
Arthurim/fundsAdmin pull request #1
Opened 2022-06-07 13:49 UTC by yvesleconte

Resolves issue #4

2022-06-08 07:28 UTC, Arthurim reviewed
As you're putting all the functions in a new file, can you confirm which ones are really new?

2022-06-08 07:28 UTC, Arthurim commented on navUtils-Aeglos.py
> +FILE_PATH = r''  # Enter the file directory between the quotation marks
For the sake of having the cleanest code possible, let's have the directory, eg: C:/dev/data/ and the file name "Agleos.xlsx" and only the directory path is to be inputed manually.

2022-06-08 07:28 UTC, Arthurim commented on navUtils-Aeglos.py
> +FILE_PATH = r''  # Enter the file directory between the quotation marks
Also, comments above the line never on the same line

2022-06-08 07:29 UTC, Arthurim commented on navUtils.py
> +
Let's minimise the number of differences please, revert this change

2022-06-10 13:02 UTC, Arthurim commented on navUtils-Aeglos.py
> +FILE_PATH = r'C:\dev\data\Aeglos.xlsx'
no need for the "r" and use only forward slashes "/"

2022-06-10 13:29 UTC, Arthurim commented on navUtils-Aeglos.py
> +
Please add a flag READ_FROM_LOCAL = True

2022-06-10 13:40 UTC, Arthurim commented on navUtils-Aeglos.py
> +FILE_PATH = r'C:\dev\data\Aeglos.xlsx'
Also let's leave only the path to the **folder**, then in the function we do PATH +"Aeglos.xlsx" because we want to enforce the fact that this file will always be named like this

2022-06-11 15:17 UTC, yvesleconte commented on navUtils-Aeglos.py
> +def read_aeglos(sheet_name):
New function

2022-06-11 15:17 UTC, yvesleconte commented on navUtils-Aeglos.py
> +
New function

2022-06-11 15:17 UTC, yvesleconte commented on navUtils-Aeglos.py
> +
Updated function

2022-06-11 15:17 UTC, yvesleconte commented on navUtils-Aeglos.py
> +
New function

2022-06-11 15:18 UTC, yvesleconte commented on navUtils-Aeglos.py
> +
Updated function

2022-06-11 15:18 UTC, yvesleconte commented on navUtils-Aeglos.py
> +
Updated function

2022-06-11 15:18 UTC, yvesleconte commented on navUtils-Aeglos.py
> +
Updated function

2022-06-11 15:20 UTC, yvesleconte commented on navUtils-Aeglos.py
> +
Updated function, theoretically it should work according to the official documentation of pandas, but it doesn't. (to do)

2022-06-11 15:46 UTC, Arthurim commented on navUtils-Aeglos.py
> +
ok gonna have a lok

2022-06-11 15:46 UTC, Arthurim commented on navUtils.py
> +
please address

2022-06-12 12:08 UTC, Arthurim commented on navUtils-Aeglos.py
> +        writer = pd.ExcelWriter(FILE_PATH, engine='openpyxl', mode="a", if_sheet_exists="overlay")
`FILE_PATH + FILE_NAME`

2022-06-12 12:16 UTC, Arthurim commented on navUtils-Aeglos.py
> +
Found out. What's your version of pandas? I upgraded to 1.4.2 and it works for me

2022-06-12 12:17 UTC, Arthurim commented on navUtils-Aeglos.py
> +    pnl_all_executions["Investment Date"] = pnl_all_executions["Investment Date"].dt.strftime(DATE_FORMAT)
`pnl_all_executions["Investment Date"] = pd.to_datetime(pnl_all_executions["Investment Date"]).dt.strftime(DATE_FORMAT)`

2022-06-12 12:17 UTC, Arthurim commented on navUtils-Aeglos.py
> +    pnl_all_executions["MtM Date"] = pnl_all_executions["MtM Date"].dt.strftime(DATE_FORMAT)
`pnl_all_executions["MtM Date"] = pd.to_datetime(pnl_all_executions["MtM Date"]).dt.strftime(DATE_FORMAT)
`

2022-06-12 12:27 UTC, Arthurim commented on navUtils-Aeglos.py
> +FILE_NAME = 'Aeglos.xlsx'
Maybe rename to `AEGLOS_FILE_NAME` ?
I like the idea of having all the read/write functions for both Aeglos and Fangorn in a single file, wdyt?

2022-06-12 12:30 UTC, Arthurim requested changes
For the sake of shorter and cleaner files we can maybe split functions into
- `read_write_excels.py` that contains the read and write functions for both Aeglos and Fangorn
- `nav_utils.py` that contains the computing functions
Wdyt?
(in any case rename navUtil-Aeglos to something all lowercase + underscore, please do the same for navUtils as well)

2022-06-12 13:22 UTC, yvesleconte commented on navUtils-Aeglos.py
> +FILE_NAME = 'Aeglos.xlsx'
Sure, I just found it clearer to have different files to get started.

2022-06-14 20:14 UTC, yvesleconte commented on navUtils-Aeglos.py
> +FILE_PATH = r''  # Enter the file directory between the quotation marks
Done

2022-06-14 20:18 UTC, Arthurim commented on navUtils.py
> +
Ignore, Pycharm is telling us to leave 2 blank lines I guess?

2022-06-14 20:19 UTC, yvesleconte commented on navUtils.py
> +
Done

2022-06-14 20:20 UTC, yvesleconte commented on navUtils-Aeglos.py
> +FILE_PATH = r'C:\dev\data\Aeglos.xlsx'
Done

2022-06-14 20:21 UTC, yvesleconte commented on navUtils-Aeglos.py
> +# new
Done

2022-06-14 20:21 UTC, yvesleconte commented on navUtils-Aeglos.py
> +
Done

2022-06-14 20:21 UTC, yvesleconte commented on navUtils-Aeglos.py
> +    return pd.read_excel(FILE_PATH, sheet_name, engine='openpyxl', decimal=',', parse_dates=True, on_bad_lines='skip')
Done

2022-06-14 20:21 UTC, yvesleconte commented on navUtils-Aeglos.py
> +    return read_aeglos_local_sheet('Trades')
Done

2022-06-14 20:52 UTC, yvesleconte commented on navUtils-Aeglos.py
> +    pnl_all_executions["MtM Date"] = pnl_all_executions["MtM Date"].dt.strftime(DATE_FORMAT)
Done

2022-06-14 20:52 UTC, yvesleconte commented on navUtils-Aeglos.py
> +    pnl_all_executions["Investment Date"] = pnl_all_executions["Investment Date"].dt.strftime(DATE_FORMAT)
Done

2022-06-14 21:20 UTC, Arthurim commented on navUtils-Aeglos.py
> +        writer = pd.ExcelWriter(FILE_PATH, engine='openpyxl', mode="a", if_sheet_exists="overlay")
Not really I can still see only `FILE_PATH`

2022-06-14 21:51 UTC, Arthurim approved these changes
- [x] just check it runs fine on local

2022-06-15 17:20 UTC, Arthurim commented on nav_utils_aeglos.py
> +def write_dataFrame_to_aeglos(df, sheet):
In this function we want to write the whole df as the whole sheet not just append it so do:
```
def write_dataFrame_to_aeglos(df, sheet):
    if READ_FROM_LOCAL:
        wb = load_workbook(FILE_PATH + FILE_NAME_AEGLOS)
        ws = wb[sheet]
        idx = wb.sheetnames.index(sheet)
        wb.remove(ws)
        wb.create_sheet(sheet, idx)
        ws = wb[sheet]
        for r in dataframe_to_rows(df, index=False, header=True):
             ws.append(r)
        wb.save(FILE_PATH + FILE_NAME_AEGLOS)
    else:
        gc = gspread.service_account(filename='C:/dev/amiable-octane-340913-90b8fb61522d.json')
        sh = gc.open("Aeglos")
        ws = sh.worksheet(sheet)
        gd.set_with_dataframe(ws, df)
```

2022-06-15 17:31 UTC, Arthurim commented on nav_utils_aeglos.py
> +    return pd.read_excel(FILE_PATH + FILE_NAME_AEGLOS, sheet_name, engine='openpyxl', parse_dates=True)
Add this before the return statement
```
    // Some magic to allow reading formulas as values otherwise we get NaNs
    app = xl.App(visible=False)
    book = app.books.open(FILE_PATH + FILE_NAME_AEGLOS)
    book.save()
    app.kill()
```

2022-06-15 17:32 UTC, Arthurim commented on nav_utils_aeglos.py
> +    return pd.read_excel(FILE_PATH + FILE_NAME_AEGLOS, sheet_name, engine='openpyxl', parse_dates=True)
+ `import xlwings as xl`

2022-06-15 17:39 UTC, Arthurim commented on nav_utils_aeglos.py
> +    write_dataFrame_to_aeglos(pnl_all_executions, "MtM PnL")
Move the to datetime calls just before the `write_dataFrame_to_aeglos` this is going to solve the date issues

2022-06-16 15:45 UTC, yvesleconte commented on nav_utils_aeglos.py
> +    write_dataFrame_to_aeglos(pnl_all_executions, "MtM PnL")
Done

2022-06-16 15:45 UTC, yvesleconte commented on nav_utils_aeglos.py
> +    return pd.read_excel(FILE_PATH + FILE_NAME_AEGLOS, sheet_name, engine='openpyxl', parse_dates=True)
Done

2022-06-16 15:59 UTC, merged